DROP TABLE ORDERS IF EXISTS;

CREATE TABLE ORDERS (
  ORDERID INTEGER NOT NULL PRIMARY KEY,
  INSTRUMENTID INTEGER,
  CLORDID  VARCHAR(50),
  PRICE DOUBLE,
  QUANTITY DOUBLE,
  SIDE VARCHAR(4),
  ORDERSTATE VARCHAR(3)
);

